url: "http://thecheckin.densitypop.com"
episode_bucket: "http://thecheckin.s3.amazonaws.com/"
pygments: true
exclude: [bin, script, Gemfile, Gemfile.lock, episodes]
markdown: kramdown
permalink: pretty
destination: public
paginate: 10

kramdown:
  entity_output: symbolic

